[project]
name = "rlhf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=3.0.0",
    "google-generativeai>=0.8.1",
    "numpy<2",
    "torch>=2.1.2",
    "transformers>=4.40.0",
    "trl[dev]==0.11.0",
]
